import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
const read=(p)=>readFileSync(new URL("../"+p,import.meta.url),"utf8");
const cargo=read("src-tauri/Cargo.lock");
const web=JSON.parse(read("web-dashboard/package-lock.json"));
const remotion=JSON.parse(read("remotion-runtime/package-lock.json"));
const rootGitignore=read(".gitignore");
const attested=read("scripts/run-attested.mjs");
const webCI=read(".github/workflows/web-dashboard-ci.yml");
const remotionCI=read(".github/workflows/remotion-ci.yml");
test("A24 all three REAL generated lockfiles exist and are parseable",()=>{
 assert.match(cargo,/^# This file is automatically @generated by Cargo\./);
 assert.match(cargo,/^version = 4$/m);
 assert.ok((cargo.match(/\[\[package\]\]/g)||[]).length>200);
 assert.match(cargo,/checksum = "[0-9a-f]{64}"/);
 assert.equal(web.lockfileVersion,3);
 assert.equal(remotion.lockfileVersion,3);
 assert.equal(web.name,"shuvi-web-dashboard");
 assert.equal(remotion.name,"shuvi-remotion-runtime");
 assert.ok(Object.keys(web.packages||{}).length>20);
 assert.ok(Object.keys(remotion.packages||{}).length>100);
});
test("A24 generated package roots agree with versioned manifests",()=>{
 for(const dir of ["web-dashboard","remotion-runtime"]){
   const manifest=JSON.parse(read(dir+"/package.json"));
   const lock=JSON.parse(read(dir+"/package-lock.json"));
   assert.equal(lock.name,manifest.name);
   assert.equal(lock.version,manifest.version);
   assert.deepEqual(lock.packages[""].dependencies||{},manifest.dependencies||{});
   assert.deepEqual(lock.packages[""].devDependencies||{},manifest.devDependencies||{});
 }
});
test("A24 Rust Cargo lock cannot be ignored or quietly re-resolved",()=>{
 assert.doesNotMatch(rootGitignore,/^src-tauri\/Cargo\.lock$/m);
 assert.match(attested,/args:\["check","--manifest-path","src-tauri\/Cargo.toml","--locked"\]/);
 assert.match(attested,/args:\["test","--manifest-path","src-tauri\/Cargo.toml","--lib","--locked"\]/);
});
test("A24 nested Node CI installs are locked and fail if dependency manifest drifts",()=>{
 assert.match(webCI,/run: npm ci/);
 assert.doesNotMatch(webCI,/run: npm install\s*$/m);
 assert.match(remotionCI,/npm ci --prefix remotion-runtime --ignore-scripts --no-audit --no-fund/);
});
